server:
  port: 12000
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/vv5626/springcloud-dev84.git
  rabbitmq:
    host: 192.168.128.128 #docker上面的Ip
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh #springcloudBus 可以让CONFIG的配置文件及时刷新