server:
  port: 9011
spring:
  application:
    name: springcloud-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true  #跨域访问
zuul:
  routes:
    springcloud-base:
      path: /base/**
      serviceId: springcloud-base